INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10100000  ', 1, '10000000  ', 'ANIMALES VIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10110000  ', 1, '10000000  ', 'PRODUCTOS PARA ANIMALES DOMÉSTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10120000  ', 1, '10000000  ', 'COMIDA DE ANIMALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10130000  ', 1, '10000000  ', 'RECIPIENTES Y HÁBITAT PARA ANIMALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10140000  ', 1, '10000000  ', 'PRODUCTOS DE TALABARTERÍA Y ARREO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10150000  ', 1, '10000000  ', 'SEMILLAS, BULBOS, PLÁNTULAS Y ESQUEJES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10160000  ', 1, '10000000  ', 'PRODUCTOS DE FLORICULTURA Y SILVICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10170000  ', 1, '10000000  ', 'FERTILIZANTES Y NUTRIENTES PARA PLANTAS Y HERBICIDAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10190000  ', 1, '10000000  ', 'PRODUCTOS PARA EL CONTROL DE PLAGAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10200000  ', 1, '10000000  ', 'ROSALES VIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10210000  ', 1, '10000000  ', 'PLANTAS VIVAS DE ESPECIES O VARIEDADES DE FLORES ALTAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10220000  ', 1, '10000000  ', 'PLANTAS VIVAS DE ESPECIES O VARIEDADES DE FLORES BAJAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10230000  ', 1, '10000000  ', 'CRISANTEMOS VIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10240000  ', 1, '10000000  ', 'CLAVELES VIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10250000  ', 1, '10000000  ', 'ORQUÍDEAS VIVAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10300000  ', 1, '10000000  ', 'ROSAS FRESCAS CORTADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10310000  ', 1, '10000000  ', 'BOUQUETS CORTADOS FRESCOS DE ESPECIES O VARIEDADES DE FLORES ALTAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10320000  ', 1, '10000000  ', 'BOUQUETS CORTADOS FRESCOS DE ESPECIES O VARIEDADES DE FLORES BAJAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10330000  ', 1, '10000000  ', 'CRISANTEMOS CORTADOS FRESCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10340000  ', 1, '10000000  ', 'BOUQUETS FLORALES CORTADOS FRESCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10350000  ', 1, '10000000  ', 'CLAVELES CORTADOS FRESCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10360000  ', 1, '10000000  ', 'ORQUÍDEAS CORTADAS FRESCAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10400000  ', 1, '10000000  ', 'ROSAS CORTADAS SECAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10410000  ', 1, '10000000  ', 'BOUQUETS CORTADOS SECOS DE ESPECIES O VARIEDADES DE FLORES ALTAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10420000  ', 1, '10000000  ', 'BOUQUETS CORTADOS SECOS DE ESPECIES O VARIEDADES DE FLORES BAJAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10430000  ', 1, '10000000  ', 'CRISANTEMOS CORTADOS SECOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10440000  ', 1, '10000000  ', 'CLAVELES CORTADOS SECOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10450000  ', 1, '10000000  ', 'ORQUÍDEAS CORTADAS SECAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('10500000  ', 1, '10000000  ', 'FOLLAJE CORTADO FRESCO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11100000  ', 1, '11000000  ', 'MINERALES, MINERALES METÁLICOS Y METALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11110000  ', 1, '11000000  ', 'TIERRA Y PIEDRA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11120000  ', 1, '11000000  ', 'PRODUCTOS NO COMESTIBLES DE PLANTA Y SILVICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11130000  ', 1, '11000000  ', 'PRODUCTOS ANIMALES NO COMESTIBLES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11140000  ', 1, '11000000  ', 'CHATARRA Y MATERIALES DE DESECHO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11150000  ', 1, '11000000  ', 'FIBRA, HILOS E HILADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11160000  ', 1, '11000000  ', 'TEJIDOS Y MATERIALES DE CUERO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11170000  ', 1, '11000000  ', 'ALEACIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11180000  ', 1, '11000000  ', 'ÓXIDO METÁLICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('11190000  ', 1, '11000000  ', 'DESECHOS METÁLICOS Y CHATARRA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12130000  ', 1, '12000000  ', 'MATERIALES EXPLOSIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12140000  ', 1, '12000000  ', 'ELEMENTOS Y GASES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12160000  ', 1, '12000000  ', 'ADITIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12170000  ', 1, '12000000  ', 'COLORANTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12180000  ', 1, '12000000  ', 'CERAS Y ACEITES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12190000  ', 1, '12000000  ', 'SOLVENTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('12350000  ', 1, '12000000  ', 'COMPUESTOS Y MEZCLAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('13100000  ', 1, '13000000  ', 'CAUCHO Y ELASTÓMEROS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('13110000  ', 1, '13000000  ', 'RESINAS Y COLOFONIAS Y OTROS MATERIALES DERIVADOS DE RESINA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('14100000  ', 1, '14000000  ', 'MATERIALES DE PAPEL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('14110000  ', 1, '14000000  ', 'PRODUCTOS DE PAPEL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('14120000  ', 1, '14000000  ', 'PAPEL PARA USO INDUSTRIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('15100000  ', 1, '15000000  ', 'COMBUSTIBLES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('15110000  ', 1, '15000000  ', 'COMBUSTIBLES GASEOSOS Y ADITIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('15120000  ', 1, '15000000  ', 'LUBRICANTES, ACEITES, GRASAS Y ANTICORROSIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('15130000  ', 1, '15000000  ', 'COMBUSTIBLE PARA REACTORES NUCLEARES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('20100000  ', 1, '20000000  ', 'MAQUINARIA Y EQUIPO DE MINERÍA Y EXPLOTACIÓN DE CANTERAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('20110000  ', 1, '20000000  ', 'EQUIPO DE PERFORACIÓN Y EXPLOTACIÓN DE POZOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('20120000  ', 1, '20000000  ', 'EQUIPO PARA PERFORACIÓN Y EXPLORACIÓN DE PETRÓLEO Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('20130000  ', 1, '20000000  ', 'MATERIALES PARA PERFORACIÓN Y OPERACIONES DE PETRÓLEO Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('20140000  ', 1, '20000000  ', 'EQUIPO DE PRODUCCIÓN Y OPERACIÓN DE PETRÓLEO Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('21100000  ', 1, '21000000  ', 'MAQUINARIA Y EQUIPO PARA AGRICULTURA, SILVICULTURA Y PAISAJISMO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('21110000  ', 1, '21000000  ', 'EQUIPO DE PESCA Y ACUICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('22100000  ', 1, '22000000  ', 'MAQUINARIA Y EQUIPO PESADO DE CONSTRUCCIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23100000  ', 1, '23000000  ', 'MAQUINARIA PARA EL PROCESAMIENTO DE MATERIAS PRIMAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23110000  ', 1, '23000000  ', 'MAQUINARIA PARA EL PROCESAMIENTO DE PETRÓLEO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23120000  ', 1, '23000000  ', 'MAQUINARIA Y ACCESORIOS DE TEXTILES Y TEJIDOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23130000  ', 1, '23000000  ', 'MAQUINARIA Y EQUIPOS LAPIDARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23140000  ', 1, '23000000  ', 'MAQUINARIA DE REPARACIÓN Y ACCESORIOS PARA MARROQUINERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23150000  ', 1, '23000000  ', 'MAQUINARIA, EQUIPO Y SUMINISTROS DE PROCESOS INDUSTRIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23160000  ', 1, '23000000  ', 'MÁQUINAS, EQUIPO Y SUMINISTROS PARA FUNDICIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23180000  ', 1, '23000000  ', 'EQUIPO INDUSTRIAL PARA ALIMENTOS Y BEBIDAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23190000  ', 1, '23000000  ', 'MEZCLADORES Y SUS PARTES Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23200000  ', 1, '23000000  ', 'EQUIPAMIENTO PARA TRANSFERENCIA DE MASA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23210000  ', 1, '23000000  ', 'MAQUINARIA DE FABRICACIÓN ELECTRÓNICA, EQUIPO Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23220000  ', 1, '23000000  ', 'EQUIPO Y MAQUINARIA DE PROCESAMIENTO DE POLLOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23230000  ', 1, '23000000  ', 'EQUIPO Y MAQUINARIA DE PROCESAMIENTO DE MADERA Y ASERRADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23240000  ', 1, '23000000  ', 'MAQUINARIA Y ACCESORIOS PARA CORTAR METALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23250000  ', 1, '23000000  ', 'MAQUINARIA Y ACCESORIOS PARA EL FORMADO DE METALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23260000  ', 1, '23000000  ', 'MAQUINARIA Y ACCESORIOS PARA HACER PROTOTIPOS RÁPIDOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23270000  ', 1, '23000000  ', 'MAQUINARIA Y ACCESORIOS Y SUMINISTROS PARA SOLDADURA DE TODAS LAS CLASES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23280000  ', 1, '23000000  ', 'MAQUINARIA PARA EL TRATAMIENTO DE METAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23290000  ', 1, '23000000  ', 'HERRAMIENTAS DE MAQUINADO INDUSTRIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('23300000  ', 1, '23000000  ', 'MAQUINARIA Y EQUIPO PARA CABLE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('24100000  ', 1, '24000000  ', 'MAQUINARIA Y EQUIPO PARA MANEJO DE MATERIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('24110000  ', 1, '24000000  ', 'RECIPIENTES Y ALMACENAMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('24120000  ', 1, '24000000  ', 'MATERIALES DE EMPAQUE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('24130000  ', 1, '24000000  ', 'REFRIGERACIÓN INDUSTRIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('24140000  ', 1, '24000000  ', 'SUMINISTROS DE EMBALAJE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25100000  ', 1, '25000000  ', 'VEHÍCULOS DE MOTOR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25110000  ', 1, '25000000  ', 'TRANSPORTE MARÍTIMO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25120000  ', 1, '25000000  ', 'MAQUINARIA Y EQUIPO PARA FERROCARRIL Y TRANVÍAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25130000  ', 1, '25000000  ', 'AERONAVES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25150000  ', 1, '25000000  ', 'NAVES ESPACIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25160000  ', 1, '25000000  ', 'BICICLETAS NO MOTORIZADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25170000  ', 1, '25000000  ', 'COMPONENTES Y SISTEMAS DE TRANSPORTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25180000  ', 1, '25000000  ', 'CARROCERÍAS Y REMOLQUES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25190000  ', 1, '25000000  ', 'EQUIPO PARA SERVICIOS DE TRANSPORTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('25200000  ', 1, '25000000  ', 'SISTEMAS Y COMPONENTES Y EQUIPOS AEROESPACIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('26100000  ', 1, '26000000  ', 'FUENTES DE ENERGÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('26110000  ', 1, '26000000  ', 'BATERÍAS Y GENERADORES Y TRANSMISIÓN DE ENERGÍA CINÉTICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('26120000  ', 1, '26000000  ', 'ALAMBRES, CABLES Y ARNESES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('26130000  ', 1, '26000000  ', 'GENERACIÓN DE ENERGÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('26140000  ', 1, '26000000  ', 'MAQUINARIA Y EQUIPO PARA ENERGÍA ATÓMICA O NUCLEAR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('27110000  ', 1, '27000000  ', 'HERRAMIENTAS DE MANO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('27120000  ', 1, '27000000  ', 'MAQUINARIA Y EQUIPO HIDRÁULICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('27130000  ', 1, '27000000  ', 'MAQUINARIA Y EQUIPO NEUMÁTICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('27140000  ', 1, '27000000  ', 'HERRAMIENTAS ESPECIALIZADAS AUTOMOTRICES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30100000  ', 1, '30000000  ', 'COMPONENTES ESTRUCTURALES Y FORMAS BÁSICAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30110000  ', 1, '30000000  ', 'HORMIGÓN, CEMENTO Y YESO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30120000  ', 1, '30000000  ', 'CARRETERAS Y PAISAJE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30130000  ', 1, '30000000  ', 'PRODUCTOS DE CONSTRUCCIÓN ESTRUCTURALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30140000  ', 1, '30000000  ', 'AISLAMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30150000  ', 1, '30000000  ', 'MATERIALES PARA ACABADO DE EXTERIORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30160000  ', 1, '30000000  ', 'MATERIALES DE ACABADO DE INTERIORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30170000  ', 1, '30000000  ', 'PUERTAS Y VENTANAS Y VIDRIO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30180000  ', 1, '30000000  ', 'INSTALACIONES DE PLOMERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30190000  ', 1, '30000000  ', 'EQUIPO DE APOYO PARA CONSTRUCCIÓN Y MANTENIMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30240000  ', 1, '30000000  ', 'COMPONENTES DE CONSTRUCCIÓN DE ESTRUCTURA PORTÁTIL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30250000  ', 1, '30000000  ', 'ESTRUCTURAS Y MATERIALES DE MINERÍA SUBTERRÁNEA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('30260000  ', 1, '30000000  ', 'MATERIALES ESTRUCTURALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31100000  ', 1, '31000000  ', 'PIEZAS DE FUNDICIÓN Y ENSAMBLES DE PIEZAS DE FUNDICIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31110000  ', 1, '31000000  ', 'EXTRUSIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31120000  ', 1, '31000000  ', 'PIEZAS FUNDIDAS MAQUINADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31130000  ', 1, '31000000  ', 'FORJADURAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31140000  ', 1, '31000000  ', 'MOLDURAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31150000  ', 1, '31000000  ', 'CUERDA, CADENA, CABLE, ALAMBRE Y CORREA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31160000  ', 1, '31000000  ', 'FERRETERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31170000  ', 1, '31000000  ', 'RODAMIENTOS, COJINETES RUEDAS Y ENGRANAJES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31180000  ', 1, '31000000  ', 'EMPAQUES, GLÁNDULAS, FUNDAS Y CUBIERTAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31190000  ', 1, '31000000  ', 'MATERIALES DE AFILADO PULIDO Y ALISADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31200000  ', 1, '31000000  ', 'ADHESIVOS Y SELLADORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31210000  ', 1, '31000000  ', 'PINTURAS Y BASES Y ACABADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31220000  ', 1, '31000000  ', 'EXTRACTOS DE TEÑIR Y DE CURTIR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31230000  ', 1, '31000000  ', 'MATERIA PRIMA EN PLACAS O BARRAS LABRADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31240000  ', 1, '31000000  ', 'ÓPTICA INDUSTRIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31250000  ', 1, '31000000  ', 'SISTEMAS DE CONTROL NEUMÁTICO, HIDRÁULICO O ELÉCTRICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31260000  ', 1, '31000000  ', 'CUBIERTAS, CAJAS Y ENVOLTURAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31270000  ', 1, '31000000  ', 'PIEZAS HECHAS A MÁQUINA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31280000  ', 1, '31000000  ', 'COMPONENTES DE PLACA Y ESTAMPADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31290000  ', 1, '31000000  ', 'EXTRUSIONES MAQUINADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31300000  ', 1, '31000000  ', 'FORJAS LABRADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31310000  ', 1, '31000000  ', 'ENSAMBLES DE TUBERÍA FABRICADA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31320000  ', 1, '31000000  ', 'ENSAMBLES FABRICADOS DE MATERIAL EN BARRAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31330000  ', 1, '31000000  ', 'ENSAMBLES ESTRUCTURALES FABRICADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31340000  ', 1, '31000000  ', 'ENSAMBLES DE LÁMINA FABRICADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31350000  ', 1, '31000000  ', 'ENSAMBLES DE TUBERÍA FABRICADA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31360000  ', 1, '31000000  ', 'ENSAMBLES DE PLACA FABRICADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31370000  ', 1, '31000000  ', 'REFRACTARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31380000  ', 1, '31000000  ', 'IMANES Y MATERIALES MAGNÉTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31390000  ', 1, '31000000  ', 'MAQUINADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31400000  ', 1, '31000000  ', 'EMPAQUES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31410000  ', 1, '31000000  ', 'SELLOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('31420000  ', 1, '31000000  ', 'PARTES SINTERIZADAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32100000  ', 1, '32000000  ', 'CIRCUITOS IMPRESOS, CIRCUITOS INTEGRADOS Y MICRO ENSAMBLAJES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32110000  ', 1, '32000000  ', 'DISPOSITIVO SEMICONDUCTOR DISCRETO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32120000  ', 1, '32000000  ', 'COMPONENTES PASIVOS DISCRETOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32130000  ', 1, '32000000  ', 'PIEZAS DE COMPONENTES Y HARDWARE ELECTRÓNICOS Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32140000  ', 1, '32000000  ', 'DISPOSITIVOS DE TUBO ELECTRÓNICO Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('32150000  ', 1, '32000000  ', 'DISPOSITIVOS Y COMPONENTES Y ACCESORIOS DE CONTROL DE AUTOMATIZACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('39100000  ', 1, '39000000  ', 'LÁMPARAS Y BOMBILLAS Y COMPONENTES PARA LÁMPARAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('39110000  ', 1, '39000000  ', 'ILUMINACIÓN, ARTEFACTOS Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('39120000  ', 1, '39000000  ', 'EQUIPOS, SUMINISTROS Y COMPONENTES ELÉCTRICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('39130000  ', 1, '39000000  ', 'DISPOSITIVOS Y ACCESORIOS Y SUMINISTROS DE MANEJO DE CABLE ELÉCTRICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40100000  ', 1, '40000000  ', 'CALEFACCIÓN, VENTILACIÓN Y CIRCULACIÓN DEL AIRE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40140000  ', 1, '40000000  ', 'DISTRIBUCIÓN DE FLUIDOS Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40150000  ', 1, '40000000  ', 'BOMBAS Y COMPRESORES INDUSTRIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40160000  ', 1, '40000000  ', 'FILTRADO Y PURIFICACIÓN INDUSTRIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40170000  ', 1, '40000000  ', 'INSTALACIONES DE TUBOS Y ENTUBAMIENTOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('40180000  ', 1, '40000000  ', 'INSTALACIONES DE TUBOS Y TUBERÍAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('41100000  ', 1, '41000000  ', 'EQUIPO DE LABORATORIO Y CIENTÍFICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('41110000  ', 1, '41000000  ', 'INSTRUMENTOS DE MEDIDA, OBSERVACIÓN Y ENSAYO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('41120000  ', 1, '41000000  ', 'SUMINISTROS Y ACCESORIOS DE LABORATORIO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42120000  ', 1, '42000000  ', 'EQUIPOS Y SUMINISTROS VETERINARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42130000  ', 1, '42000000  ', 'TELAS Y VESTIDOS MÉDICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42140000  ', 1, '42000000  ', 'SUMINISTROS, PRODUCTOS DE TRATAMIENTO Y CUIDADO DEL ENFERMO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42150000  ', 1, '42000000  ', 'EQUIPOS Y SUMINISTROS DENTALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42160000  ', 1, '42000000  ', 'EQUIPO DE DIÁLISIS Y SUMINISTROS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42170000  ', 1, '42000000  ', 'PRODUCTOS PARA LOS SERVICIOS MÉDICOS DE URGENCIAS Y CAMPO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42180000  ', 1, '42000000  ', 'PRODUCTOS DE EXAMEN Y CONTROL DEL PACIENTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42190000  ', 1, '42000000  ', 'PRODUCTOS DE CENTRO MÉDICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42200000  ', 1, '42000000  ', 'PRODUCTOS DE HACER IMÁGENES DIAGNÓSTICAS MÉDICAS Y DE MEDICINA NUCLEAR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42210000  ', 1, '42000000  ', 'AYUDA PARA PERSONAS CON DESAFÍOS FÍSICOS PARA VIVIR INDEPENDIENTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42220000  ', 1, '42000000  ', 'PRODUCTOS PARA ADMINISTRACIÓN INTRAVENOSA Y ARTERIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42230000  ', 1, '42000000  ', 'NUTRICIÓN CLÍNICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42240000  ', 1, '42000000  ', 'PRODUCTOS MEDICINALES DE DEPORTES Y ORTOPÉDICOS Y PRÓTESIS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42250000  ', 1, '42000000  ', 'PRODUCTOS DE REHABILITACIÓN Y TERAPIA OCUPACIONAL Y FÍSICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42260000  ', 1, '42000000  ', 'EQUIPO Y SUMINISTROS POST MORTEM Y FUNERARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42270000  ', 1, '42000000  ', 'PRODUCTOS DE RESUCITACIÓN, ANESTESIA Y RESPIRATORIO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42280000  ', 1, '42000000  ', 'PRODUCTOS PARA LA ESTERILIZACIÓN MÉDICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42290000  ', 1, '42000000  ', 'PRODUCTOS QUIRÚRGICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42300000  ', 1, '42000000  ', 'SUMINISTROS PARA FORMACIÓN Y ESTUDIOS DE MEDICINA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42310000  ', 1, '42000000  ', 'PRODUCTOS PARA EL CUIDADO DE HERIDAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('42320000  ', 1, '42000000  ', 'IMPLANTES ORTOPÉDICOS QUIRÚRGICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('43190000  ', 1, '43000000  ', 'DISPOSITIVOS DE COMUNICACIONES Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('43200000  ', 1, '43000000  ', 'COMPONENTES PARA TECNOLOGÍA DE LA INFORMACIÓN, DIFUSIÓN O TELECOMUNICACIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('43210000  ', 1, '43000000  ', 'EQUIPO INFORMÁTICO Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('43220000  ', 1, '43000000  ', 'EQUIPOS O PLATAFORMAS Y ACCESORIOS DE REDES MULTIMEDIA O DE VOZ Y DATOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('43230000  ', 1, '43000000  ', 'SOFTWARE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('44100000  ', 1, '44000000  ', 'MAQUINARIA, SUMINISTROS Y ACCESORIOS DE OFICINA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('44110000  ', 1, '44000000  ', 'ACCESORIOS DE OFICINA Y ESCRITORIO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('44120000  ', 1, '44000000  ', 'SUMINISTROS DE OFICINA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('45100000  ', 1, '45000000  ', 'EQUIPO DE IMPRENTA Y PUBLICACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('45110000  ', 1, '45000000  ', 'EQUIPOS DE AUDIO Y VIDEO PARA PRESENTACIÓN Y COMPOSICIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('45120000  ', 1, '45000000  ', 'EQUIPO DE VÍDEO, FILMACIÓN O FOTOGRAFÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('45130000  ', 1, '45000000  ', 'MEDIOS FOTOGRÁFICOS Y DE GRABACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('45140000  ', 1, '45000000  ', 'SUMINISTROS FOTOGRÁFICOS PARA CINE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46100000  ', 1, '46000000  ', 'ARMAS LIGERAS Y MUNICIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46110000  ', 1, '46000000  ', 'ARMAS DE GUERRA CONVENCIONALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46120000  ', 1, '46000000  ', 'MISILES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46130000  ', 1, '46000000  ', 'COHETES Y SUBSISTEMAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46140000  ', 1, '46000000  ', 'LANZADORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46150000  ', 1, '46000000  ', 'PROTECCIÓN DEL ORDEN PÚBLICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46160000  ', 1, '46000000  ', 'SEGURIDAD Y CONTROL PÚBLICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46170000  ', 1, '46000000  ', 'SEGURIDAD, VIGILANCIA Y DETECCIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46180000  ', 1, '46000000  ', 'SEGURIDAD Y PROTECCIÓN PERSONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46190000  ', 1, '46000000  ', 'PROTECCIÓN CONTRA INCENDIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('46200000  ', 1, '46000000  ', 'EQUIPO DE ENTRENAMIENTO DE SEGURIDAD FÍSICA E INDUSTRIAL, DEFENSA Y ORDEN PÚBLICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('47100000  ', 1, '47000000  ', 'TRATAMIENTO, SUMINISTROS Y ELIMINACIÓN DE AGUA Y AGUAS RESIDUALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('47110000  ', 1, '47000000  ', 'EQUIPO INDUSTRIAL DE LAVANDERÍA Y LAVADO EN SECO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('47120000  ', 1, '47000000  ', 'EQUIPO DE ASEO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('47130000  ', 1, '47000000  ', 'SUMINISTROS DE ASEO Y LIMPIEZA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('48100000  ', 1, '48000000  ', 'EQUIPOS DE SERVICIOS DE ALIMENTACIÓN PARA INSTITUCIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('48110000  ', 1, '48000000  ', 'MÁQUINAS EXPENDEDORAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('48120000  ', 1, '48000000  ', 'EQUIPO DE JUEGO O DE APOSTAR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('48130000  ', 1, '48000000  ', 'EQUIPO Y MATERIALES FUNERARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49100000  ', 1, '49000000  ', 'COLECCIONABLES Y CONDECORACIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49120000  ', 1, '49000000  ', 'EQUIPOS Y ACCESORIOS PARA ACAMPADA Y EXTERIORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49130000  ', 1, '49000000  ', 'EQUIPOS DE PESCA Y CAZA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49140000  ', 1, '49000000  ', 'EQUIPOS PARA DEPORTES ACUÁTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49150000  ', 1, '49000000  ', 'EQUIPOS PARA DEPORTES DE INVIERNO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49160000  ', 1, '49000000  ', 'EQUIPOS DEPORTIVOS PARA CAMPOS Y CANCHAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49170000  ', 1, '49000000  ', 'EQUIPOS DE GIMNASIA Y BOXEO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49180000  ', 1, '49000000  ', 'JUEGOS, EQUIPO DE TIRO Y MESA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49200000  ', 1, '49000000  ', 'EQUIPO PARA ENTRENAMIENTO FÍSICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49210000  ', 1, '49000000  ', 'OTROS DEPORTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49220000  ', 1, '49000000  ', 'EQUIPO Y ACCESORIOS PARA DEPORTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('49240000  ', 1, '49000000  ', 'EQUIPO DE RECREO, PARQUES INFANTILES Y EQUIPO Y SUMINISTROS DE NATACIÓN Y DE SPA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50100000  ', 1, '50000000  ', 'FRUTOS SECOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50110000  ', 1, '50000000  ', 'PRODUCTOS DE CARNE Y AVES DE CORRAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50120000  ', 1, '50000000  ', 'PESCADOS Y MARISCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50130000  ', 1, '50000000  ', 'PRODUCTOS LÁCTEOS Y HUEVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50150000  ', 1, '50000000  ', 'ACEITES Y GRASAS COMESTIBLES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50160000  ', 1, '50000000  ', 'CHOCOLATES, AZÚCARES, EDULCORANTES Y PRODUCTOS DE CONFITERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50170000  ', 1, '50000000  ', 'CONDIMENTOS Y CONSERVANTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50180000  ', 1, '50000000  ', 'PRODUCTOS DE PANADERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50190000  ', 1, '50000000  ', 'ALIMENTOS PREPARADOS Y CONSERVADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50200000  ', 1, '50000000  ', 'BEBIDAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50210000  ', 1, '50000000  ', 'TABACO Y PRODUCTOS DE FUMAR Y SUBSTITUTOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50220000  ', 1, '50000000  ', 'PRODUCTOS DE CEREALES Y LEGUMBRES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50300000  ', 1, '50000000  ', 'FRUTA FRESCA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50310000  ', 1, '50000000  ', 'FRUTA ORGÁNICA FRESCA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50320000  ', 1, '50000000  ', 'FRUTA SECA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50330000  ', 1, '50000000  ', 'FRUTA ORGÁNICA SECA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50340000  ', 1, '50000000  ', 'FRUTA CONGELADA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50350000  ', 1, '50000000  ', 'FRUTA ORGÁNICA CONGELADA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50360000  ', 1, '50000000  ', 'FRUTA EN LATA O EN FRASCO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50370000  ', 1, '50000000  ', 'FRUTA ORGÁNICA EN LATA O EN FRASCO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50380000  ', 1, '50000000  ', 'PURÉ DE FRUTAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50400000  ', 1, '50000000  ', 'VEGETALES FRESCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50410000  ', 1, '50000000  ', 'VEGETALES ORGÁNICOS FRESCOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50420000  ', 1, '50000000  ', 'VEGETALES SECOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50430000  ', 1, '50000000  ', 'VEGETALES ORGÁNICOS SECOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50440000  ', 1, '50000000  ', 'VEGETALES CONGELADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50450000  ', 1, '50000000  ', 'VEGETALES ORGÁNICOS CONGELADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50460000  ', 1, '50000000  ', 'VEGETALES EN LATA O EN FRASCO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('50470000  ', 1, '50000000  ', 'VEGETALES ORGÁNICOS EN LATA O EN FRASCO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51100000  ', 1, '51000000  ', 'MEDICAMENTOS ANTIINFECCIOSOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51110000  ', 1, '51000000  ', 'AGENTES ANTITUMORALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51120000  ', 1, '51000000  ', 'MEDICAMENTOS CARDIOVASCULARES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51130000  ', 1, '51000000  ', 'MEDICAMENTOS HEMATÓLOGOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51140000  ', 1, '51000000  ', 'MEDICAMENTOS PARA EL SISTEMA NERVIOSO CENTRAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51150000  ', 1, '51000000  ', 'MEDICAMENTOS PARA EL SISTEMA NERVIOSO AUTÓNOMO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51160000  ', 1, '51000000  ', 'MEDICAMENTOS QUE AFECTAN AL SISTEMA RESPIRATORIO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51170000  ', 1, '51000000  ', 'MEDICAMENTOS QUE AFECTAN AL SISTEMA GASTROINTESTINAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51180000  ', 1, '51000000  ', 'HORMONAS Y ANTAGONISTAS HORMONALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51190000  ', 1, '51000000  ', 'AGENTES QUE AFECTAN EL AGUA Y LOS ELECTROLITOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51200000  ', 1, '51000000  ', 'MEDICAMENTOS INMUNOMODULADORES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51210000  ', 1, '51000000  ', 'CATEGORÍAS DE MEDICAMENTOS VARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51240000  ', 1, '51000000  ', 'FÁRMACOS QUE AFECTAN A LOS OÍDOS, LOS OJOS, LA NARIZ Y LA PIEL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('51250000  ', 1, '51000000  ', 'SUPLEMENTOS ALIMENTICIOS VETERINARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52100000  ', 1, '52000000  ', 'REVESTIMIENTOS DE SUELOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52120000  ', 1, '52000000  ', 'ROPA DE CAMA, MANTELERÍAS, PAÑOS DE COCINA Y TOALLAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52130000  ', 1, '52000000  ', 'TRATAMIENTOS DE VENTANAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52140000  ', 1, '52000000  ', 'APARATOS ELECTRODOMÉSTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52150000  ', 1, '52000000  ', 'UTENSILIOS DE COCINA DOMÉSTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52160000  ', 1, '52000000  ', 'ELECTRÓNICA DE CONSUMO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('52170000  ', 1, '52000000  ', 'TRATAMIENTOS DE PARED DOMÉSTICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('53100000  ', 1, '53000000  ', 'ROPA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('53110000  ', 1, '53000000  ', 'CALZADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('53120000  ', 1, '53000000  ', 'MALETAS, BOLSOS DE MANO, MOCHILAS Y ESTUCHES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('53130000  ', 1, '53000000  ', 'ARTÍCULOS DE TOCADOR Y CUIDADO PERSONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('53140000  ', 1, '53000000  ', 'FUENTES Y ACCESORIOS DE COSTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('54100000  ', 1, '54000000  ', 'JOYERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('54110000  ', 1, '54000000  ', 'RELOJES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('54120000  ', 1, '54000000  ', 'GEMAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('55100000  ', 1, '55000000  ', 'MEDIOS IMPRESOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('55110000  ', 1, '55000000  ', 'MATERIAL ELECTRÓNICO DE REFERENCIA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('55120000  ', 1, '55000000  ', 'ETIQUETADO Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('56100000  ', 1, '56000000  ', 'MUEBLES DE ALOJAMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('56110000  ', 1, '56000000  ', 'MUEBLES COMERCIALES E INDUSTRIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('56120000  ', 1, '56000000  ', 'MOBILIARIO INSTITUCIONAL, ESCOLAR Y EDUCATIVO Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('56130000  ', 1, '56000000  ', 'MUEBLES Y ACCESORIOS PARA MERCHANDISING', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('56140000  ', 1, '56000000  ', 'ADORNOS PARA EL HOGAR', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('60100000  ', 1, '60000000  ', 'MATERIALES DIDÁCTICOS PROFESIONALES Y DE DESARROLLO Y ACCESORIOS Y SUMINISTROS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('60110000  ', 1, '60000000  ', 'DECORACIONES Y SUMINISTROS DEL AULA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('60120000  ', 1, '60000000  ', 'EQUIPO, ACCESORIOS Y SUMINISTROS DE ARTE Y MANUALIDADES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('60130000  ', 1, '60000000  ', 'INSTRUMENTOS MUSICALES, PIEZAS Y ACCESORIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('60140000  ', 1, '60000000  ', 'JUGUETES Y JUEGOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70100000  ', 1, '70000000  ', 'PESQUERÍAS Y ACUICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70110000  ', 1, '70000000  ', 'HORTICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70120000  ', 1, '70000000  ', 'SERVICIOS DE ANIMALES VIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70130000  ', 1, '70000000  ', 'PREPARACIÓN, GESTIÓN Y PROTECCIÓN DEL TERRENO Y DEL SUELO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70140000  ', 1, '70000000  ', 'PRODUCCIÓN, GESTIÓN Y PROTECCIÓN DE CULTIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70150000  ', 1, '70000000  ', 'SILVICULTURA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70160000  ', 1, '70000000  ', 'FAUNA Y FLORA SILVESTRES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('70170000  ', 1, '70000000  ', 'DESARROLLO Y VIGILANCIA DE RECURSOS HIDRÁULICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71100000  ', 1, '71000000  ', 'SERVICIOS DE MINERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71110000  ', 1, '71000000  ', 'SERVICIOS DE PERFORACIÓN Y PROSPECCIÓN PETROLÍFERA Y DE GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71120000  ', 1, '71000000  ', 'SERVICIOS DE CONSTRUCCIÓN Y PERFORACIÓN DE POZOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71130000  ', 1, '71000000  ', 'SERVICIOS DE AUMENTO DE LA EXTRACCIÓN Y PRODUCCIÓN DE GAS Y PETRÓLEO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71140000  ', 1, '71000000  ', 'SERVICIOS DE RESTAURACIÓN Y RECUPERACIÓN DE GAS Y PETRÓLEO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71150000  ', 1, '71000000  ', 'SERVICIOS DE PROCESAMIENTO Y GESTIÓN DE DATOS DE PETRÓLEO Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('71160000  ', 1, '71000000  ', 'SERVICIOS DE GERENCIA DE PROYECTOS EN POZOS DE PETRÓLEO Y GAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('72100000  ', 1, '72000000  ', 'SERVICIOS DE MANTENIMIENTO Y REPARACIONES DE CONSTRUCCIONES E INSTALACIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('72110000  ', 1, '72000000  ', 'SERVICIOS DE CONSTRUCCIÓN DE EDIFICACIONES RESIDENCIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('72120000  ', 1, '72000000  ', 'SERVICIOS DE CONSTRUCCIÓN DE EDIFICACIONES NO RESIDENCIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('72140000  ', 1, '72000000  ', 'SERVICIOS DE CONSTRUCCIÓN PESADA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('72150000  ', 1, '72000000  ', 'SERVICIOS DE MANTENIMIENTO Y CONSTRUCCIÓN DE COMERCIO ESPECIALIZADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73100000  ', 1, '73000000  ', 'INDUSTRIAS DE PLÁSTICOS Y PRODUCTOS QUÍMICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73110000  ', 1, '73000000  ', 'INDUSTRIAS DE LA MADERA Y EL PAPEL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73120000  ', 1, '73000000  ', 'INDUSTRIAS DEL METAL Y DE MINERALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73130000  ', 1, '73000000  ', 'INDUSTRIAS DE ALIMENTOS Y BEBIDAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73140000  ', 1, '73000000  ', 'INDUSTRIAS DE FIBRAS, TEXTILES Y DE TEJIDOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73150000  ', 1, '73000000  ', 'SERVICIOS DE APOYO A LA FABRICACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73160000  ', 1, '73000000  ', 'FABRICACIÓN DE MAQUINARIA Y EQUIPO DE TRANSPORTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73170000  ', 1, '73000000  ', 'FABRICACIÓN DE PRODUCTOS ELÉCTRICOS E INSTRUMENTOS DE PRECISIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('73180000  ', 1, '73000000  ', 'SERVICIOS DE MAQUINADO Y PROCESADO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('76100000  ', 1, '76000000  ', 'SERVICIOS DE DESCONTAMINACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('76110000  ', 1, '76000000  ', 'SERVICIOS DE ASEO Y LIMPIEZA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('76120000  ', 1, '76000000  ', 'ELIMINACIÓN Y TRATAMIENTO DE DESECHOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('76130000  ', 1, '76000000  ', 'LIMPIEZA DE RESIDUOS TÓXICOS Y PELIGROSOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('77100000  ', 1, '77000000  ', 'GESTIÓN MEDIOAMBIENTAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('77110000  ', 1, '77000000  ', 'PROTECCIÓN MEDIOAMBIENTAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('77120000  ', 1, '77000000  ', 'SEGUIMIENTO, CONTROL Y REHABILITACIÓN DE LA CONTAMINACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('77130000  ', 1, '77000000  ', 'SERVICIOS DE SEGUIMIENTO, CONTROL O REHABILITACIÓN DE CONTAMINANTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78100000  ', 1, '78000000  ', 'TRANSPORTE DE CORREO Y CARGA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78110000  ', 1, '78000000  ', 'TRANSPORTE DE PASAJEROS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78120000  ', 1, '78000000  ', 'MANEJO Y EMBALAJE DE MATERIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78130000  ', 1, '78000000  ', 'ALMACENAJE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78140000  ', 1, '78000000  ', 'SERVICIOS DE TRANSPORTE', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('78180000  ', 1, '78000000  ', 'SERVICIOS DE MANTENIMIENTO O REPARACIONES DE TRANSPORTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80100000  ', 1, '80000000  ', 'SERVICIOS DE ASESORÍA DE GESTIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80110000  ', 1, '80000000  ', 'SERVICIOS DE RECURSOS HUMANOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80120000  ', 1, '80000000  ', 'SERVICIOS LEGALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80130000  ', 1, '80000000  ', 'SERVICIOS INMOBILIARIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80140000  ', 1, '80000000  ', 'COMERCIALIZACIÓN Y DISTRIBUCIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80150000  ', 1, '80000000  ', 'POLÍTICA COMERCIAL Y SERVICIOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('80160000  ', 1, '80000000  ', 'SERVICIOS DE ADMINISTRACIÓN DE EMPRESAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81100000  ', 1, '81000000  ', 'SERVICIOS PROFESIONALES DE INGENIERÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81110000  ', 1, '81000000  ', 'SERVICIOS INFORMÁTICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81120000  ', 1, '81000000  ', 'ECONOMÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81130000  ', 1, '81000000  ', 'ESTADÍSTICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81140000  ', 1, '81000000  ', 'TECNOLOGÍAS DE FABRICACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81150000  ', 1, '81000000  ', 'SERVICIOS DE PEDOLOGÍA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('81160000  ', 1, '81000000  ', 'ENTREGA DE SERVICIOS DE TECNOLOGÍA DE INFORMACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82100000  ', 1, '82000000  ', 'PUBLICIDAD', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82110000  ', 1, '82000000  ', 'ESCRITURA Y TRADUCCIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82120000  ', 1, '82000000  ', 'SERVICIOS DE REPRODUCCIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82130000  ', 1, '82000000  ', 'SERVICIOS FOTOGRÁFICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82140000  ', 1, '82000000  ', 'DISEÑO GRÁFICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('82150000  ', 1, '82000000  ', 'ARTISTAS E INTÉRPRETES PROFESIONALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('83100000  ', 1, '83000000  ', 'SERVICIOS PÚBLICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('83110000  ', 1, '83000000  ', 'SERVICIOS DE MEDIOS DE TELECOMUNICACIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('83120000  ', 1, '83000000  ', 'SERVICIOS DE INFORMACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('84100000  ', 1, '84000000  ', 'FINANZAS DE DESARROLLO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('84110000  ', 1, '84000000  ', 'SERVICIOS DE CONTABILIDAD Y AUDITORIAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('84120000  ', 1, '84000000  ', 'BANCA E INVERSIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('84130000  ', 1, '84000000  ', 'SERVICIOS DE SEGUROS Y PENSIONES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('84140000  ', 1, '84000000  ', 'AGENCIAS DE CRÉDITO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85100000  ', 1, '85000000  ', 'SERVICIOS INTEGRALES DE SALUD', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85110000  ', 1, '85000000  ', 'PREVENCIÓN Y CONTROL DE ENFERMEDADES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85120000  ', 1, '85000000  ', 'PRÁCTICA MÉDICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85130000  ', 1, '85000000  ', 'CIENCIA MÉDICA, INVESTIGACIÓN Y EXPERIMENTACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85140000  ', 1, '85000000  ', 'MEDICINA ALTERNATIVA Y HOLÍSTICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85150000  ', 1, '85000000  ', 'SERVICIOS ALIMENTICIOS Y DE NUTRICIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85160000  ', 1, '85000000  ', 'SERVICIOS DE MANTENIMIENTO, RENOVACIÓN Y REPARACIÓN DE EQUIPO MÉDICO QUIRÚRGICO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('85170000  ', 1, '85000000  ', 'SERVICIOS DE MUERTE Y SOPORTE AL FALLECIMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('86100000  ', 1, '86000000  ', 'FORMACIÓN PROFESIONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('86110000  ', 1, '86000000  ', 'SISTEMAS EDUCATIVOS ALTERNATIVOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('86120000  ', 1, '86000000  ', 'INSTITUCIONES EDUCATIVAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('86130000  ', 1, '86000000  ', 'SERVICIOS EDUCATIVOS ESPECIALIZADOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('86140000  ', 1, '86000000  ', 'INSTALACIONES EDUCATIVAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90100000  ', 1, '90000000  ', 'RESTAURANTES Y CATERING (SERVICIOS DE COMIDAS Y BEBIDAS)', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90110000  ', 1, '90000000  ', 'INSTALACIONES HOTELERAS, ALOJAMIENTOS Y CENTROS DE ENCUENTROS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90120000  ', 1, '90000000  ', 'FACILITACIÓN DE VIAJES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90130000  ', 1, '90000000  ', 'ARTES INTERPRETATIVAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90140000  ', 1, '90000000  ', 'DEPORTES COMERCIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('90150000  ', 1, '90000000  ', 'SERVICIOS DE ENTRETENIMIENTO', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('91100000  ', 1, '91000000  ', 'ASPECTO PERSONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('91110000  ', 1, '91000000  ', 'ASISTENCIA DOMÉSTICA Y PERSONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('92100000  ', 1, '92000000  ', 'ORDEN PÚBLICO Y SEGURIDAD', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('92110000  ', 1, '92000000  ', 'SERVICIOS MILITARES O DEFENSA NACIONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('92120000  ', 1, '92000000  ', 'SEGURIDAD Y PROTECCIÓN PERSONAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93100000  ', 1, '93000000  ', 'SISTEMAS E INSTITUCIONES POLÍTICAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93110000  ', 1, '93000000  ', 'CONDICIONES SOCIOPOLÍTICAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93120000  ', 1, '93000000  ', 'RELACIONES INTERNACIONALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93130000  ', 1, '93000000  ', 'AYUDA Y ASISTENCIA HUMANITARIA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93140000  ', 1, '93000000  ', 'SERVICIOS COMUNITARIOS Y SOCIALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93150000  ', 1, '93000000  ', 'SERVICIOS DE ADMINISTRACIÓN Y FINANCIACIÓN PÚBLICA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93160000  ', 1, '93000000  ', 'TRIBUTACIÓN', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('93170000  ', 1, '93000000  ', 'POLÍTICA Y REGULACIÓN COMERCIAL', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('94100000  ', 1, '94000000  ', 'ORGANIZACIONES LABORALES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('94110000  ', 1, '94000000  ', 'ORGANIZACIONES RELIGIOSAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('94120000  ', 1, '94000000  ', 'CLUBES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('94130000  ', 1, '94000000  ', 'ORGANIZACIONES, ASOCIACIONES Y MOVIMIENTOS CÍVICOS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('95100000  ', 1, '95000000  ', 'PARCELAS DE TIERRA', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('95110000  ', 1, '95000000  ', 'VÍAS', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('95120000  ', 1, '95000000  ', 'ESTRUCTURAS Y EDIFICIOS PERMANENTES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('95130000  ', 1, '95000000  ', 'ESTRUCTURAS Y EDIFICIOS MÓVILES', NULL)
INSERT INTO unspsc.Family([Id],[VersionId],[SegmentId],[FamilyTitle],[FamilyDefinition])VALUES ('95140000  ', 1, '95000000  ', 'ESTRUCTURAS Y EDIFICIOS PREFABRICADOS', NULL)