/*
<documentation>
	<object type="U" schema="auth" name="Salts" />
	<summary>Salts Table</summary>
	<author>Jheison J. Mayta C.</author>
	<createdAt>2024.10.27</createdAt>
	<sourceLink></sourceLink>
</documentation>
*/
CREATE TABLE [auth].[Salts]
(
	  [Id]			[BIGINT] IDENTITY(1,1)	NOT NULL
	, [UserId]		[CHAR](24)				NOT NULL
	, [Salt]		[NVARCHAR](255)			NOT NULL
	, [HostName]	[NVARCHAR](128)			NULL
	, [AppName]		[NVARCHAR](128)			NULL
	, [UserName]	[NVARCHAR](128)			NULL
	, [CreatedAt]	[DATETIMEOFFSET]		NULL
	, [UpdatedAt]	[DATETIMEOFFSET]		NULL
) ON [PRIMARY]
GO
-- CONSTRAINTS
ALTER TABLE [auth].[Salts]
	ADD CONSTRAINT PK_Salts_Id
		PRIMARY KEY CLUSTERED ([Id]);
GO
ALTER TABLE [auth].[Salts]
	ADD CONSTRAINT DF_Salts_CreatedAt
		DEFAULT SYSDATETIMEOFFSET()
			FOR [CreatedAt];
GO
-- INDEXES
CREATE NONCLUSTERED INDEX IX_Salts_UserId
	ON [auth].[Salts]([UserId])
		INCLUDE ([Salt],[CreatedAt],[UpdatedAt])
GO
-- 
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'User Salt Table'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Identifier autogenerated'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'Id';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'User Identifier (auth.Users)'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'UserId';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Salt string'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'Salt';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Workstation name where the operation was performed.'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'HostName';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Client application name where the operation was performed.'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'AppName';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'User name that performed the last operation in the record.'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'UserName';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Registration date and time (contains time zone information)'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'CreatedAt';
GO
EXEC sp_addextendedproperty
  @name			= N'MS_Description'
, @value		= 'Last update date and time (includes time zone information)'
, @level0type	= 'SCHEMA'		, @level0name	= N'auth'
, @level1type	= 'TABLE'		, @level1name	= N'Salts'
, @level2type	= 'COLUMN'		, @level2name	= N'UpdatedAt';
GO
